#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    arr.sort()
    min_sum = sum(arr[:-1]) # everything but last element
    max_sum = sum(arr[1:]) # everything but first element
    print(min_sum, max_sum)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
    

UPDATED:
    
    def miniMaxSum(arr):
    
    min = sum(sorted(arr)[:4])
    max = sum(sorted(arr)[1:])
    print(min, max)


