#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    i = 0
    pos = list()
    zero = list()
    neg = list()
    if 0 <= len(arr) <= 100:
        while i < len(arr):
            if 0 < arr[i] <= 100:
                pos.append(arr[i])
            elif arr[i] == 0:
                zero.append(arr[i])
            elif -100 <= arr[i] < 0:
                neg.append(arr[i])
            else:
                print("Integer in array is smaller than -100 or greater than 100.")
            i = i + 1
    else:
        print("Error: Array must have a length between 0 to 100 integers.")    
         
    print(round(float(len(pos)/len(arr)), 6))
    print(round(float(len(neg)/len(arr)), 6))
    print(round(float(len(zero)/len(arr)), 6))
            

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)

    
    
 UPDATED:
        
        
        
 def plusMinus(arr):
    pos = list()
    neg = list()
    zero = list()
    for numb in arr:
        if numb > 0:
            pos.append(numb)
        elif numb == 0:
            zero.append(numb)
        else:
            neg.append(numb)
    print(round(len(pos)/len(arr), 6))
    print(round(len(neg)/len(arr), 6))
    print(round(len(zero)/len(arr), 6))
