#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'timeConversion' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def timeConversion(s): # my code (below)
    if s[0:2] == "12" and s[-2:] == "AM":
        t = s.replace(s[0:2], str(int(s[0:2])*0)*2)
        time = t.replace(t[-2:], "")
    elif int(s[0:2]) < 12 and s[-2:] == "AM":
        time = s.replace(s[-2:], "")
    elif s[0:2] == "12" and s[-2:] == "PM":
        time = s.replace(s[-2:], "")
    else:
        t = s.replace(s[0:2], str(int(s[0:2])+12))
        time = t.replace(s[-2:], "")
    return time
    
    
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    result = timeConversion(s)

    fptr.write(result + '\n')

    fptr.close()
    
    
UPDATED:
    
    if int(s[0:2]) < 12 and s[-2:] == "AM":
        s = s[0:8]
        return s
    elif s[0:2] == "12" and s[-2:] == "AM":
        t = "00" + s[2:8]
        return t
    elif int(s[0:2]) < 12 and s[-2:] == "PM":
        u = int(s[0:2]) + 12
        v = str(u) + s[2:8]
        return v
    else: 
        w = s[0:8]
        return w
